version: '3.5'
services:
  mssql:
    container_name: mssql-db
    hostname: mssql-db
    build:
      context: ./sqlserver
      dockerfile: Dockerfile
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Admin_123'
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_PID: 'Developer' 
      MSSQL_TCP_PORT: 1433 
    ports: 
      - "1455:1433"
    volumes:
      - ./sqlserver/volumes/data:/var/opt/mssql/data
      - ./sqlserver/volumes/log:/var/opt/mssql/log
      - ./sqlserver/volumes/secrets:/var/opt/mssql/secrets  
    restart: unless-stopped  